// Generated by https://quicktype.io

export interface CountriesGeoJSON {
	type: string;
	features: Feature[];
}

export interface Feature {
	type: FeatureType;
	properties: Properties;
	geometry: Geometry;
}

export interface Geometry {
	type: GeometryType;
	coordinates: Array<Array<Array<number[] | number>>>;
}

export enum GeometryType {
	MultiPolygon = 'MultiPolygon',
	Polygon = 'Polygon',
}

export interface Properties {
	ADMIN: string;
	ISO_A3: string;
}

export enum FeatureType {
	Feature = 'Feature',
}
